services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - monorepo_starterkit_data_dev:/var/lib/postgresql/data

volumes:
  monorepo_starterkit_data_dev: