services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-database}
    ports:
      - "5435:5432" # Sesuai perubahan port agar tidak konflik di VPS
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-database}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    # Menggunakan Image dari GHCR (sudah di-build di GitHub Actions)
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/tracking-sholat-api:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-database}?schema=public
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  platform:
    # Menggunakan Image dari GHCR (sudah di-build di GitHub Actions)
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/tracking-sholat-platform:latest
    restart: always
    environment:
      - VITE_API_BASE_URL=https://api.sholat.anaslabs.my.id
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
