name: Deploy Web & API ke Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to IDCloudHost using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            # Memaksa load path agar pnpm/pm2 terbaca
            export PNPM_HOME="/home/anas/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH:/home/anas/.nvm/versions/node/v24.12.0/bin"
            
            # Pindah direktori
            cd ~/tracking-sholat
            
            # Pull update
            git checkout main
            git pull origin main

            pnpm install --frozen-lockfile --network-timeout 100000

            # Database & Migration
            cd apps/api
            pnpm prisma generate
            # Matikan postgres lokal jika ada (menggunakan sudo jika perlu, tapi coba dulu tanpa ini jika sudah mati)
            # sudo systemctl stop postgresql 
            pnpm prisma migrate deploy
            cd ../..

            pnpm build

            # Docker DB (Pastikan port 5432 lokal sudah mati agar baris ini tidak error)
            docker compose up -d db

            pm2 start ecosystem.config.cjs || pm2 reload ecosystem.config.cjs
            pm2 save
